

CREATE TABLE <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST (
    SOURCE_SCHEMA VARCHAR(256) NOT NULL,
    SOURCE_NAME VARCHAR(256) NOT NULL,
    TARGET_SCHEMA VARCHAR(256) NOT NULL,
    TARGET_NAME VARCHAR(256) NOT NULL,
    STATUS VARCHAR(256) NULL
);

-- Insert one pair of Source Table and Target Table 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC_PC_COND', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_COND'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC_PC_INV_H', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_INV_H'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC_PC_INV_I', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_INV_I'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC_PC_IRNLNK', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_IRNLNK'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC_PC_MATERIAL', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_MATERIAL'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC_PC_PARTNERS', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_PARTNERS'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC_PC_PG_CAT', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_PG_CAT'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC_PC_PG_CH', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_PG_CH'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC_PC_PG_CS', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_PG_CS'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC_PC_PG_H', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_PG_H'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC_PC_PG_I', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_PG_I'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC_PC_SAMPLE', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_SAMPLE'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC_PC_SUBSCRIBER', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_SUBSCRIBER'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC_PC_SUBSCRIPTION', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_SUBSCRIPTION'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC_PC_SUBSCR_OD', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_SUBSCR_OD'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Customizing.ORGTYP', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_CUSTOMIZING_ORGTYP'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Customizing.ORGTYP_T', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_CUSTOMIZING_ORGTYP_T'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Customizing.PARTRL', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_CUSTOMIZING_PARTRL'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Customizing.PARTTY', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_CUSTOMIZING_PARTTY'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Customizing.PRRL_T', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_CUSTOMIZING_PRRL_T'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Customizing.PRTY_T', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_CUSTOMIZING_PRTY_T'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::DocumentRepository.DOCREP', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_DOCUMENTREPOSITORY_DOCREP'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::DocumentRepository.DOCREP_CNFG', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_DOCUMENTREPOSITORY_DOCREP_CNFG'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Extractor.H2H_ACF', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_EXTRACTOR_H2H_ACF'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Extractor.H2H_ICF', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_EXTRACTOR_H2H_ICF'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Generic.CREDENTIALS', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_GENERIC_CREDENTIALS'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Logs.ALOG_H', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_LOGS_ALOG_H'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Logs.ALOG_M', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_LOGS_ALOG_M'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Logs.MSG_LOG', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_LOGS_MSG_LOG'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Notification.EVENT_DEST', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_NOTIFICATION_EVENT_DEST'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::PaymentGateway.PG_CAT', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_PAYMENTGATEWAY_PG_CAT'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::PaymentGateway.PG_CH', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_PAYMENTGATEWAY_PG_CH'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::PaymentGateway.PG_CPREF', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_PAYMENTGATEWAY_PG_CPREF'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::PaymentGateway.PG_CS', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_PAYMENTGATEWAY_PG_CS'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::PaymentGateway.PG_H', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_PAYMENTGATEWAY_PG_H'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::PaymentGateway.PG_I', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_PAYMENTGATEWAY_PG_I'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Reports.MIS_SCHEDULER', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_REPORTS_MIS_SCHEDULER'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Survey.SURVEY_DATA', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_SURVEY_SURVEY_DATA'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Typesets.ATST', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_TYPESETS_ATST'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Typesets.ATST_T', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_TYPESETS_ATST_T'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Typesets.ATYP', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_TYPESETS_ATYP'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Typesets.ATYP_T', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_TYPESETS_ATYP_T'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Typesets.TSET', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_TYPESETS_TSET'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Typesets.TSET_T', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_TYPESETS_TSET_T'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Typesets.TYPS', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_TYPESETS_TYPS'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Typesets.TYPS_T', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_TYPESETS_TYPS_T'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Typesets.TYPVAL', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_TYPESETS_TYPVAL'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Typesets.VALHLP', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_TYPESETS_VALHLP'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Upload.UPLD', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_UPLOAD_UPLD'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Upload.UPLD_I', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_UPLOAD_UPLD_I'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::UserMgmt.USRATH', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_USERMGMT_USRATH'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::UserMgmt.USRLGN', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_USERMGMT_USRLGN'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::UserMgmt.USRPRT', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_USERMGMT_USRPRT'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PC::Workflow.APPROVAL', '<TARGET_SCHEMA_NAME>', 'ARTEC_PC_WORKFLOW_APPROVAL'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::BusinessPartner.BP', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_BUSINESSPARTNER_BP'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::BusinessPartner.BPCNTP', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_BUSINESSPARTNER_BPCNTP'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::BusinessPartner.COR', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_BUSINESSPARTNER_COR'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::BusinessPartner.SCP', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_BUSINESSPARTNER_SCP'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::BusinessPartner.SCP_1', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_BUSINESSPARTNER_SCP_1'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::BusinessPartner.SCP_2', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_BUSINESSPARTNER_SCP_2'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::BusinessPartner.SCP_3', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_BUSINESSPARTNER_SCP_3'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::BusinessPartner.SCP_4', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_BUSINESSPARTNER_SCP_4'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::BusinessPartner.VENDORCOR', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_BUSINESSPARTNER_VENDORCOR'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Config.AGGR', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_CONFIG_AGGR'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Config.AGGR_FACILITY', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_CONFIG_AGGR_FACILITY'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Config.DCCNFG', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_CONFIG_DCCNFG'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Config.DFCNFG', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_CONFIG_DFCNFG'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Config.IDCNFG', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_CONFIG_IDCNFG'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Config.IFSC', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_CONFIG_IFSC'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Config.OPCNFG', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_CONFIG_OPCNFG'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Config.PFCNFG', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_CONFIG_PFCNFG'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Config.RFCNFG', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_CONFIG_RFCNFG'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Config.SCCNFG', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_CONFIG_SCCNFG'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::ESignContract.ESIGNCAL', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_ESIGNCONTRACT_ESIGNCAL'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::EnhancementLimit.ENHLMT', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_ENHANCEMENTLIMIT_ENHLMT'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Payments.AP_PAYM', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_PAYMENTS_AP_PAYM'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Payments.AP_PAYMI', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_PAYMENTS_AP_PAYMI'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Payments.OPENITEMS', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_PAYMENTS_OPENITEMS'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Payments.OPENITEM_HEADER', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_PAYMENTS_OPENITEM_HEADER'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Payments.PAYM', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_PAYMENTS_PAYM'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Payments.PAYMI', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_PAYMENTS_PAYMI'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Reports.CF_MIS', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_REPORTS_CF_MIS'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Reports.LSR_1', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_REPORTS_LSR_1'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::Reports.SCF_DLR_OS', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_REPORTS_SCF_DLR_OS'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::SupplyChainFinance.SCF', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_SUPPLYCHAINFINANCE_SCF'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::SupplyChainFinance.SCF1', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_SUPPLYCHAINFINANCE_SCF1'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::SupplyChainFinance.SCF2', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_SUPPLYCHAINFINANCE_SCF2'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::SupplyChainFinance.SCF3', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_SUPPLYCHAINFINANCE_SCF3'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::SupplyChainFinance.SCF4', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_SUPPLYCHAINFINANCE_SCF4'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::SupplyChainFinance.SCF_RETRY', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_SUPPLYCHAINFINANCE_SCF_RETRY'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::User.COMMN', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_USER_COMMN'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.PY::User.UACCNT', '<TARGET_SCHEMA_NAME>', 'ARTEC_PY_USER_UACCNT'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC.SP::VisitGeo.VSTGEO', '<TARGET_SCHEMA_NAME>', 'ARTEC_SP_VISITGEO_VSTGEO'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC_ID6_ARTERIA_SCF1_ET', '<TARGET_SCHEMA_NAME>', 'ARTEC_ID6_ARTERIA_SCF1_ET'); 
INSERT INTO <MIGRATION_USER>.XSC2CAP_DATA_MIGRATION_TABLE_LIST(SOURCE_SCHEMA, SOURCE_NAME, TARGET_SCHEMA, TARGET_NAME) VALUES ('AGGR0008_1', 'ARTEC_ID6_ARTERIA_SCF_ET', '<TARGET_SCHEMA_NAME>', 'ARTEC_ID6_ARTERIA_SCF_ET'); 

-- Create Table DDL for MIGRATION_PARAMETERS
CREATE TABLE <MIGRATION_USER>.MIGRATION_PARAMETERS(PARAMETER_NAME NVARCHAR(256), PARAMETER_VALUE NVARCHAR(5000)); 

-- Enable xsc2cap data migration mode by inserting an instruction
INSERT INTO <MIGRATION_USER>.MIGRATION_PARAMETERS VALUES ('enable_xsc2cap_migration', 'TRUE');
