// using from './xsjs/lib/XSUI/Services/custom-service';
// using from './xsjs/lib/ARTEC_SDI/SCF1/custom-service';
// using from './xsjs/lib/ARTEC_SDI/BP/custom-service';
// using from './xsjs/lib/ARTEC_SDI/UACCNT/custom-service';
// using from './xsjs/lib/ARTEC_SDI/PG_H/custom-service';
// using from './xsjs/lib/ARTEC_SDI/XSJS/custom-service';
// using from './xsjs/lib/ARTEC_SDI/SCF/custom-service';
// using from './xsjs/lib/ARTEC_SDI/ODATA/service';
// using from './xsjs/lib/ARTEC_SDI/CV/service';
// using from './xsjs/lib/ARTEC/PC/ApplicationNo/custom-service';
// using from './xsjs/lib/ARTEC/PCMISGW/service';
// using from './xsjs/lib/ARTEC/NR/ApplicationNo/custom-service';
// using from './xsjs/lib/ARTEC/NR/TrackID/custom-service';
// using from './xsjs/lib/ARTEC/NR/LimitIDPrefix/custom-service';
using from './xsjs/lib/ARTEC/PYGW/service';
using from './xsjs/lib/ARTEC/PCGW/service';
// using from './xsjs/lib/ARTEC/SPGW/service';
using from './xsjs/lib/ARTEC/PUGW/service';
// using from './xsjs/lib/ARTEC/PYMISGW/service';
